# Generated by Django 5.2.4 on 2025-07-30 10:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleOfArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the example item.', max_length=255)),
                ('content', models.TextField(help_text='The full content of the example item.')),
                ('url', models.URLField(help_text='The original URL of the example item.', unique=True)),
                ('published_date', models.DateTimeField(help_text='The date and time when the item was published.')),
                ('author', models.CharField(blank=True, help_text='The author of the example item.', max_length=100, null=True)),
                ('source', models.CharField(help_text='The source of the example item.', max_length=100)),
                ('image_url', models.URLField(blank=True, help_text='An optional image URL for the example item.', null=True)),
                ('description', models.TextField(blank=True, help_text='A brief description or summary of the example item.', null=True)),
                ('example_source', models.CharField(help_text='The example source of the item.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the item was created.')),
            ],
            options={
                'verbose_name': 'Example Article',
                'verbose_name_plural': 'Example Articles',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='ExampleOfFetchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, help_text='The example source used for this operation', max_length=100, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('SUCCESS', 'Success'), ('ERROR', 'Error')], default='PENDING', help_text='Current status of the operation', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the operation started')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the operation completed', null=True)),
                ('items_fetched', models.IntegerField(default=0, help_text='Number of items fetched from the source')),
                ('items_saved', models.IntegerField(default=0, help_text='Number of items successfully saved')),
                ('error_message', models.TextField(blank=True, help_text='Error message if the operation failed')),
                ('query_params', models.JSONField(default=dict, help_text='Parameters used for the operation')),
                ('metadata', models.JSONField(default=dict, help_text='Additional metadata about the operation')),
                ('raw_data_file', models.CharField(blank=True, help_text='Path to the raw JSON data file', max_length=255)),
            ],
            options={
                'verbose_name': 'Example Fetch Log',
                'verbose_name_plural': 'Example Fetch Logs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['status', '-started_at'], name='example_exa_status_e3bacf_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExampleOfSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.TextField(blank=True, help_text='The processed summary text', null=True)),
                ('processing_model', models.CharField(default='example-model-v1', help_text='The processing model used', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current status of the processing', max_length=20)),
                ('word_count', models.IntegerField(blank=True, help_text='Number of words in the summary', null=True)),
                ('processing_cost', models.DecimalField(blank=True, decimal_places=4, help_text='Cost of processing in credits', max_digits=10, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the processing request was created')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the processing was completed', null=True)),
                ('example_item', models.ForeignKey(help_text='The example item being processed', on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='example.exampleofarticle')),
                ('requested_by', models.ForeignKey(blank=True, help_text='User who requested the processing', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Example Summary',
                'verbose_name_plural': 'Example Summaries',
                'ordering': ['-created_at'],
                'unique_together': {('example_item', 'processing_model')},
            },
        ),
    ]
